# Generated by Django 4.1.2 on 2022-10-21 20:33

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=0.5, size=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
