# Generated by Django 4.1.2 on 2022-10-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(default='1234', max_length=255),
            preserve_default=False,
        ),
    ]
